[package]
name = "truba"
version = "0.1.2"
edition = "2021"

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["sync", "rt", "rt-multi-thread", "macros", "time"] }
typemap-ors = "1.0"
parking_lot = "0.12"